Repository maciejhirsz/logos, pull requests merged in 2024-06, with the labels that each got.

#393 fix(lib): correctly handle miss for loop in loop
  logos-codegen/src/graph/regex.rs
  tests/tests/edgecase.rs
Labels: bug

#386 chore(lib): remove error branch from LUT if it is unreachable
  logos-codegen/Cargo.toml
  logos-codegen/src/generator/fork.rs
  logos-codegen/tests/codegen.rs
  logos-codegen/tests/data/no_error_lut/input.rs
  logos-codegen/tests/data/no_error_lut/output.rs
  logos-codegen/tests/data/simple/input.rs
  logos-codegen/tests/data/simple/output.rs
Labels: enhancement

#379 chore(docs): Adds graph debug documentation to book
  book/src/SUMMARY.md
  book/src/debugging.md
  logos-codegen/src/lib.rs
Labels: book
