Repository maciejhirsz/logos, pull requests merged in 2024-12, with the labels that each got.

#442 Minor readme improvments
  README.md
  RELEASE-PROCESS.md
Labels: enhancement, documentation

#451 chore(release): bump to 0.15
  Cargo.toml
  book/src/getting-started.md
  logos-cli/Cargo.toml
  logos-derive/Cargo.toml
Labels: release

#455 Fix #[regex] monospace formatting in 4.2 Token and Regex
  book/src/attributes/token_and_regex.md
Labels: book
