Repository maciejhirsz/logos, pull requests merged in 2024-11, with the labels that each got.

#438 Bump rstest to 0.23.0, the current release
  logos-codegen/Cargo.toml
Labels: dependencies

#435 fix(lib): use precise capturing on 1.82+
  .github/workflows/rustlib.yml
  Cargo.toml
  logos-codegen/Cargo.toml
  logos-codegen/build.rs
  logos-codegen/src/generator/leaf.rs
Labels: bug, continuous integration

#439 chore(book): add simple calculator example
  Cargo.toml
  book/src/SUMMARY.md
  book/src/assets/calculator_example_flow.png
  book/src/assets/calculator_example_how_evaluator_works.png
  book/src/examples.md
  book/src/examples/brainfuck.md
  book/src/examples/calculator.md
  examples/calculator.rs
Labels: book
